### ISSUE TITLE
Implement spiral algorithm in Advanced

### ISSUE THREAD

**Issue by ramdesh** [ramdesh/vmoopxrksvi#1]
We need to implement the **spiral** reading algorithm for the advanced tool. In a grid as shown below:

``` javascript
s s e m l
a i s i a
g s T h r
e a s p i
```

This will be given to us as **ssemlaisiagsThreaspi** and can be decoded to "This is a spiral message" when the algorithm is applied in counter-clockwise fashion. This needs to be applied in clockwise fashion as well.

**Comment by ChamalN** [comment]
Does the reading start from the center or one of the edges? @Kulendra

**Comment by Kulendra** [comment]
1. Reading can begin from a corner or the center.
   However, reading from center will be identical to reading from a corner and reversing it.
   Note that the reading will always begin from a corner, not from the middle of an edge.
2. The matrix/box that is drawn to spiral could be a square OR a rectangle.
3.  Reading can be done clockwise or counterclockwise.

**Comment by ramdesh** [comment]
`
The matrix/box that is drawn to spiral could be a square OR a rectangle.
`

This basically refers to checking `string.length` against square and triangular numbers, right? This might require another function to match against known square and triangular numbers.

**Comment by Kulendra** [comment]
Not necessary to implement a new function. `array factors(string)` returns an array of integer factorisations possible. It also returns the full string length as a single element if it is not possible to factorise (i.e. string length is a prime).

**Comment by ramdesh** [comment]
Will factors work? The multiplications of a known triangular number won't be triangular numbers, right?

**Comment by ChamalN** [comment]
The math for this hurts my head :P I'm just going to write a load of loops and conditions

**Comment by ramdesh** [comment]
Ah, didn't notice it was rectangular. Disregard my earlier comment. :sweat_smile:

**Comment by Kulendra** [comment]
This is resolved now. Spiral algo is implemented.

**Comment by Kulendra** [comment]
Closing as per comment above.
